version: '3.1'

services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    image: loqus:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://mongo:27017/blog
      DB_USER: root
      DB_PASS: example
